config/routes.rb
Rails.application.routes.draw do
  resources :dvds
  resources :cart_items
  resources :baskets
  resources :films
  resources :people
  resources :countries
  resources :genres
  resources :users

  root 'films#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

end

app/models/basket.rb
class Basket < ActiveRecord::Base

DELIVERY = %w(Почтой Курьерская_доставка Самовывоз)
STAT = %w(Ожидается_оплата Оплачено Доставляется Доставлено)

    has_many :cart_items
    belongs_to :user
    scope :ordering, -> { order(:name) }
    validates :user, presence:true
    validates :status, presence:true
    before_validation :set_default_delivery
    before_validation :set_default_status


    def self.edit_by?(u)
      u.try(:admin?)
    end

    def set_price
      pr=0
      self.cart_items.each  do |c|
        pr =pr + c.price*c.amount.to_i
      end
      self.price=pr
    end

    def set_default_delivery
      self.type_of_delivery||=0
    end

    def delivery_name
      type_of_delivery && DELIVERY[type_of_delivery]
    end

    def set_default_status
      self.status||=0
    end

    def status_name
      status && STAT[status]
    end

    def set_status(s)
      self.status = s
    end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:show, :edit, :update, :destroy]

  # GET /baskets
  # GET /baskets.json
  def index

    @baskets = Basket.all.page(params[:page ] )
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
    @basket.set_price
    if params[:st]
      if @basket.address || @basket.type_of_delivery == '2'

        if params[:st]==1
          p=0
          @basket.cart_items.each do |c|
            if c.amount.to_i > c.dvd.amount
              p=1
            end
          end
          if p==0
            @basket.cart_items.each do |c|
              c.dvd.amount= c.dvd.amount- c.amount.to_i
              c.dvd.amount.save
            end
          else
            redirect_to @basket, notice: 'Нет в наличии'
          end
        else
          @basket.status=params[:st]
          @basket.save
        end
      else
        redirect_to @basket, notice: 'Не указан адрес'
      end
    end

  end

  # GET /baskets/new
  def new
    @basket = Basket.new(user:@current_user)

  end

  # GET /baskets/1/edit
  def edit
    @basket.set_price
    if params[:st]
      if @basket.address || @basket.type_of_delivery == '2'

        if params[:st]==1
          p=0
          @basket.cart_items.each do |c|
            if c.amount.to_i >c.dvd.amount
              p=1
            end
          end
          if p==0
            @basket.cart_items.each do |c|
              c.dvd.amount= c.dvd.amount - c.amount.to_i
              c.dvd.amount.save
            end
          else
            redirect_to @basket, notice: 'Нет в наличии'
          end
        else
          @basket.status=params[:st]
          @basket.save
        end
      else
        redirect_to @basket, notice: 'Не указан адрес'
      end
    end

end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(basket_params)
    @basker.status = 0
    @cart_item.basket.set_price
    @basker.user = @current_user
    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baskets/1
  # PATCH/PUT /baskets/1.json
  def update
    @basket.set_price
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { render :show, status: :ok, location: @basket }
      else
        format.html { render :edit }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket.destroy
    respond_to do |format|
      format.html { redirect_to baskets_url, notice: 'Basket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basket
      @basket = Basket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basket_params
      params.require(:basket).permit(:status, :type_of_delivery, :integer, :address, :text, :user_id)
    end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/_basket.haml
=link_to basket_path(basket), class: 'list-group-item' do
  .media
    .media-body
      -if(basket.user)
        %h4.media-heading
          =basket.user.name
        -basket.set_price
        %i
          =basket.price
        %i pyб
      -if basket.status == 2
        %span.label.label-danger=basket.status_name
      -if basket.status == 1
        %span.label.label-warning=basket.status_name
      -if basket.status == 0
        %span.label.label-info=basket.status_name
      -if basket.status == 3
        %span.label.label-default=basket.status_name

app/views/baskets/_form.html.haml
= form_for @basket do |f|
  =f.hidden_field :cart_items
  =f.hidden_field :status
  - if @basket.errors.any?
    #error_explanation
      %h2= "#{pluralize(@basket.errors.count, "error")} prohibited this basket from being saved:"
      %ul
        - @basket.errors.full_messages.each do |msg|
          %li= msg

  -if @basket.status == 2
    %span.label.label-important=@basket.status_name
  -if @basket.status == 1
    %span.label.label-warning=@basket.status_name
  -if @basket.status == 0
    %span.label.label-info=@basket.status_name
  -if @basket.status == 3
    %span.label.label-default=@basket.status_name
  %br
  %br
  .form-group
    =f.label :Тип_доставки
    =f.select :type_of_delivery, Basket::DELIVERY.map.with_index{|name,i| [name,i]}, {},class: 'form-control'
  .form-group
    =f.label :Адрес_доставки
    =f.text_field :address, class: 'form-control'
  %br
    -if @basket.price
      %b Цена :
      = @basket.price
  %p
  .btn-toolbar
    = f.submit 'Готово', class: 'btn btn-danger'
    %br

-if @basket.cart_items.any?
  -@basket.cart_items.each do |f|
    =render f
  %br
  -if not User.edit_by?(@current_user)
    =link_to basket_path(@basket,st:1), class: 'btn btn-danger' do
      =fa_icon 'rub'
      Оплатить все
-else
  %h3 Корзина пуста.

app/views/baskets/edit.html.haml
.page-header
  -if User.edit_by?(@current_user)
    %h1 Корзина пользователя
    %h1=@basket.user.name
  -else
    %h1 Моя корзина
= render 'form'

app/views/baskets/index.html.haml
.page-header
  -if User.edit_by?(@current_user)
    %h1 Заказы
  -else
    %h1 Мои заказы

-if Basket.edit_by?(@current_user)
  .list-group
    =render @baskets
  =paginate @baskets
-else
  .list-group
    =render @current_user.baskets
  

app/views/baskets/new.html.haml
%h1 New basket

= render 'form'

= link_to 'Back', baskets_path

app/views/baskets/show.html.haml
.page-header
  -if User.edit_by?(@current_user)
    %h1 Заказ пользователя
    %h1=@basket.user.name
  -else
    %h1 Мой заказ


-if  User.edit_by?(@current_user)
  %br
  -if @basket.status == 1
    =link_to basket_path(@basket,st:2), class: 'btn btn-primary' do
      =fa_icon 'truck'
      Перевести на статус "Доставляется"
  -if @basket.status == 2
    =link_to basket_path(@basket,st:3), class: 'btn btn-primary' do
      =fa_icon 'check'
      Перевести на статус "Доставлено"
  -if @basket.status == 3
    =link_to @basket, data: {method: :delete, confirm: t('helpers.sure')}, class: 'btn btn-danger' do
      =fa_icon 'trash'
      Удалить
%p

%p
-if @basket.status == 2
  %span.label.label-danger=@basket.status_name
-if @basket.status == 1
  %span.label.label-warning=@basket.status_name
-if @basket.status == 0
  %span.label.label-info=@basket.status_name
-if @basket.status == 3
  %span.label.label-default=@basket.status_name

%p
  %b Тип доставки:
  = @basket.delivery_name

%p
  %b Адрес:
  = @basket.address
%p

%p
  -@basket.set_price
  %b Цена :
  = @basket.price
%p

  %b Пользователь:
  = @basket.user.name
-if not User.edit_by?(@current_user)
  -if @basket.status == 0
    =link_to edit_basket_path(@basket), class: 'btn btn-primary' do
      =fa_icon 'edit'
      Редактировать
-if User.edit_by?(@current_user)
  =link_to edit_basket_path(@basket), class: 'btn btn-primary' do
    =fa_icon 'edit'
    Редактировать
%p

-if @basket.cart_items.any?
  -@basket.cart_items.each do |f|
    =render f
  %br
  -if not User.edit_by?(@current_user)
    -if @basket.status == 0
      =link_to basket_path(@basket,st:1), class: 'btn btn-danger' do
        =fa_icon 'rub'
        Оплатить все
-else
  %h3 Корзина пуста.