config/routes.rb
Rails.application.routes.draw do
  resources :dvds
  resources :cart_items
  resources :baskets
  resources :films
  resources :people
  resources :countries
  resources :genres
  resources :users

  root 'films#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

end

app/models/film.rb
class Film < ActiveRecord::Base
  has_attached_file :cover, styles: {medium: "250x250>", thumb: "100x100>"}

  belongs_to :country
  belongs_to :genre
  belongs_to :director, class_name: 'Person'
  has_and_belongs_to_many :people, -> { ordering }
  has_many :dvds

  validates :name, presence: true
  validates :country, presence: true
  validates :director, presence: true
  validates :genre, presence: true
  validates :length, numericality: {only_integer: true, greater_than: 0}, allow_blank: true
  validates :year, numericality: {only_integer: true, greater_than: 1885}, allow_blank: true
  validate :check_people
  validates_attachment :cover, content_type: {content_type: /\Aimage\/.*\z/}


  scope :ordering, -> { order(:year, :name) }
  scope :base, ->{includes(:genre)}
  scope :full, -> { includes(:country, :genre, :director, :people) }

  attr_reader :person_tokens

  def self.edit_by?(u)
    u.try(:admin?)
  end


  def person_tokens=(val)
    self.person_ids = val.split(',')
  end


  private
  def check_people
    errors.add(:people, :blank) if people.blank?
    true
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :check_authentication, except: :index
  before_action :check_edit, except: [:index, :show]
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  def index
    @films = Film.base.ordering.page(params[:page])
  end

  def show
  end

  def new
    @film = Film.new
  end

  def edit
  end

  def create
    @film = Film.new(film_params)
    if @film.save
      redirect_to @film, notice: 'Фильм создан.'
    else
      render :new
    end
  end

  def update
    if @film.update(film_params)
      redirect_to @film, notice: 'Фильм изменен.'
    else
      render :edit
    end
  end

  def destroy
    if @film.destroy
      redirect_to films_url, notice: 'Файл удален.'
    else
      render_error("Удаление фильма невозможно", url: @film)
    end
  end

  private

  def set_film
    @film = Film.full.find(params[:id])
  end

  def film_params
    params.require(:film).permit(:name, :origin_name, :slogan, :country_id, :genre_id, :director_id, :length, :year, :trailer_url, :cover, :description, :person_tokens)
  end

  def check_edit
    render_error unless Film.edit_by?(@current_user)
  end
end

app/helpers/films_helper.rb
module FilmsHelper
  def youtube_tag(youtube_id)
    content_tag(:iframe, nil, class: 'youtube', src: "//www.youtube.com/embed/#{youtube_id}?html5=1", frameborder: 0, allowfullscreen: true)
  end
end

app/views/films/_film.html.haml
=link_to film, class: 'list-group-item' do
  .media
    -if film.cover?
      .media-left=image_tag film.cover.url(:thumb), alt: film.name, class: 'media-object'
    .media-body
      %h4.media-heading
        =film.name
      %i
        =film.genre.name
      %small.text-muted=film.year

app/views/films/_form.html.haml
= form_for @film do |f|
  =error_messages_for(@film)
  .row
    .col-md-4
      .form-group
        =f.label :name
        =f.text_field :name, class: 'form-control'
    .col-md-4
      .form-group
        =f.label :origin_name
        =f.text_field :origin_name, class: 'form-control'
    .col-md-4
      .form-group
        =f.label :cover
        =f.file_field :cover
      -if @film.cover?
        .text-center
          =link_to @film.cover.url do
            =image_tag @film.cover.url(:thumb), alt: @film.name
  .row
    .col-md-3
      .form-group
        =f.label :country_id
        =f.select :country_id, Country.ordering.map{|c| [c.name,c.id]},{}, class: 'form-control'
    .col-md-3
      .form-group
        =f.label :genre_id
        =f.select :genre_id, Genre.ordering.map{|c| [c.name,c.id]},{}, class: 'form-control'
    .col-md-2
      .form-group
        =f.label :year
        =f.text_field :year, class: 'form-control'
    .col-md-2
      .form-group
        =f.label :length
        .input-group
          =f.text_field :length, class: 'form-control'
          %span.input-group-addon мин
    .col-md-2
      .form-group
        =f.label :trailer_url
        =f.text_field :trailer_url, class: 'form-control'
  .row
    .col-md-6
      .form-group
        =f.label :slogan
        =f.text_area :slogan, rows: 3, class: 'form-control'
    .col-md-6
      .form-group
        =f.label :description
        =f.text_area :description, rows: 6, class: 'form-control'
  .row
    .col-md-4
      .form-group
        =f.label :director_id
        =f.text_field :director_id, data: {tokeninput:  people_path(format: :json),
        pre: [@film.director].compact.to_json, limit: 1}
    .col-md-8
      .form-group
        =f.label :person_tokens, Film.human_attribute_name(:people)
        =f.text_field :person_tokens, data: {tokeninput:  people_path(format: :json), pre: @film.people.to_json}
  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/films/_menu.html.haml
-if Film.edit_by?(@current_user)
  .btn-toolbar
    =link_to edit_film_path(@film), class: 'btn btn-primary' do
      =fa_icon 'edit'
      Редактировать
    =link_to @film, data: {method: :delete, confirm: t('helpers.sure')}, class: 'btn btn-danger' do
      =fa_icon 'trash'
      Удалить

app/views/films/edit.html.haml
.page-header
  %h1 Редактирование фильма
= render 'form'

app/views/films/index.html.haml
.page-header
  %h1 Фильмы
-if Film.edit_by?(@current_user)
  .btn-toolbar
    =link_to new_film_path, class: 'btn btn-primary' do
      =fa_icon 'plus'
      Новый фильм
-if @films.blank?
  .alert.alert-info Фильмов не найдено
-else
  .list-group
    =render @films
  =paginate @films

app/views/films/new.html.haml
.page-header
  %h1 Новый фильм
= render 'form'

app/views/films/show.html.haml
.page-header
  %h1
    =@film.name
    -if @film.origin_name.present?
      %small=@film.origin_name
=render 'menu'
.row
  .col-md-3
    -if @film.cover?
      =image_tag @film.cover.url(:medium), alt: @film.name, class: 'img-responsive'
  .col-md-9
    -if @film.slogan.present?
      %blockquote
        %p=@film.slogan
    %dl
      -if @film.country
        %dt=Film.human_attribute_name(:country)
        %dd=link_to @film.country.name,@film.country
      -if @film.genre
        %dt=Film.human_attribute_name(:genre)
        %dd=link_to @film.genre.name,@film.genre
      -if @film.length
        %dt=Film.human_attribute_name(:length)
        %dd
          =@film.length
          =RuPropisju.choose_plural(@film.length,'минута','минуты','минут')
      -if @film.year
        %dt=Film.human_attribute_name(:year)
        %dd=@film.year
    %div=@film.description
    -if @film.trailer_url.present?
      =youtube_tag(@film.trailer_url)

    -if @film.dvds.any?
      %h3=Film.human_attribute_name(:dvds)
      .list-group
        =render @film.dvds



    -if @film.director
      %h3=Film.human_attribute_name(:director_id)
      .list-group
        =render 'people/person', person: @film.director
    -if @film.people.any?
      %h3=Film.human_attribute_name(:people)
      .list-group
        -@film.people.each do |person|
          =render 'people/person', person: person