config/routes.rb
Rails.application.routes.draw do
  resources :dvds
  resources :cart_items
  resources :baskets
  resources :films
  resources :people
  resources :countries
  resources :genres
  resources :users

  root 'films#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

end

app/models/dvd.rb
class Dvd < ActiveRecord::Base
    has_attached_file :cover, styles: {medium: "250x250>", thumb: "100x100>"}

    belongs_to :film
    has_many :cart_item

    validates :name, presence: true
    validates :price, presence: true, numericality: {only_integer: true, greater_than: 0}
  
    validates :cover_type, presence:true
    validates_attachment :cover, content_type: {content_type: /\Aimage\/.*\z/}
    scope :full, -> { includes(:film) }

    def self.edit_by?(u)
      u.try(:admin?)
    end
end

app/controllers/dvds_controller.rb
class DvdsController < ApplicationController
  before_action :check_authentication, except: :index
  before_action :set_dvd, only: [:show, :edit, :update, :destroy]
  before_action :check_edit, except: [:index, :show]


  # GET /dvds
  # GET /dvds.json
  def index
    @dvds = Dvd.all
  end

  # GET /dvds/1
  # GET /dvds/1.json
  def show
  end

  # GET /dvds/new
  def new
    @dvd = Dvd.new
  end



  # GET /dvds/1/edit
  def edit
  end

  # POST /dvds
  # POST /dvds.json
  def create

    @dvd = Dvd.new(dvd_params)
    if not @dvd.cover?
      @dvd.cover = @dvd.film.cover
    end
    if @dvd.save
      redirect_to @dvd, notice: 'Диск создан.'
    else
      render :new
    end
  end

  # PATCH/PUT /dvds/1
  # PATCH/PUT /dvds/1.json
  def update
    if @dvd.update(dvd_params)
      redirect_to @dvd, notice: 'Диск изменен.'
    else
      render :edit
    end
  end

  # DELETE /dvd/1
  # DELETE /dvd/1.json
  def destroy
    if @dvd.destroy
      redirect_to dvds_url, notice: 'Диск удален.'
    else
      render_error("Удаление диска невозможно", url: @dvd)
    end
  end

  private

    def set_dvd
      @dvd = Dvd.full.find(params[:id])
    end

    def dvd_params
      params.require(:dvd).permit(:film_id,:cover_type, :cover, :name, :price, :amount)
    end

    def check_edit
      render_error unless Dvd.edit_by?(@current_user)
    end
end

app/helpers/dvds_helper.rb
module DvdsHelper
end

app/views/dvds/_dvd.html.haml
=link_to dvd, class: 'list-group-item' do
  .media
    -if dvd.cover?
      .media-left=image_tag dvd.cover.url(:thumb), alt: dvd.name, class: 'media-object'
    .media-body
      %h4.media-heading
        =dvd.name
      %i
        =dvd.film.name
      %br
      %small.text-muted=dvd.price
      %small.text-muted руб
      %br

app/views/dvds/_form.html.haml
= form_for @dvd do |f|
  =error_messages_for(@dvd)
  .row
    .col-md-4
      .form-group
        =f.label :Название
        =f.text_field :name, class: 'form-control'

    .col-md-4
      .form-group
        =f.label :Обложка
        =f.file_field :cover

      -if @dvd.cover?
        .text-center
          =link_to @dvd.cover.url do
            =image_tag @dvd.cover.url(:thumb), alt: @dvd.name

  .row
    .col-md-3
      .form-group
        =f.label :Фильм
        =f.select :film_id, Film.ordering.map{|c| [c.name,c.id]},{}, class: 'form-control'
    .col-md-3
      .form-group
        =f.label :Цена
        =f.text_field :price, class: 'form-control'

    .col-md-2
      .form-group
        =f.label :Тип_обложки
        =f.text_field :cover_type, class: 'form-control'




  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/dvds/_menu.html.haml
-if Dvd.edit_by?(@current_user)
  .btn-toolbar
    =link_to edit_dvd_path(@dvd), class: 'btn btn-primary' do
      =fa_icon 'edit'
      Редактировать
    =link_to @dvd, data: {method: :delete, confirm: t('helpers.sure')}, class: 'btn btn-danger' do
      =fa_icon 'trash'
      Удалить

app/views/dvds/edit.html.haml
%h1 Editing dvd

= render 'form'

= link_to 'Show', @dvd
\|
= link_to 'Back', dvds_path

app/views/dvds/index.html.haml
.page-header
  %h1 Диски
-if Film.edit_by?(@current_user)
  .btn-toolbar
    =link_to new_dvd_path, class: 'btn btn-primary' do
      =fa_icon 'plus'
      Новый диск
-if @dvds.blank?
  .alert.alert-info Дисков не найдено
-else
  .list-group
    =render @dvds

app/views/dvds/new.html.haml
.page-header
  %h1 Новый диск
= render 'form'

app/views/dvds/show.html.haml
.page-header
  %h1
    =@dvd.name
=render 'menu'
.row
.col-md-3
  -if @dvd.cover?
    =image_tag @dvd.cover.url(:medium), alt: @dvd.name, class: 'img-responsive'

.col-md-9
  %dl
    -if @dvd.film.name
      %dt='Фильм'
      %dd=link_to @dvd.film.name, @dvd.film
    -if @dvd.price
      %dt='Цена'
      %small.text-muted=@dvd.price
      %small.text-muted руб

    -if @dvd.cover_type
      %dt='Тип обложки'
      %dd=@dvd.cover_type


-if not Dvd.edit_by?(@current_user)
  .btn-toolbar

    =link_to new_cart_item_path(key:@dvd.price, disk: @dvd.id),id: @dvd, class: 'btn btn-danger' do
      =fa_icon 'shopping-basket'
      В корзину