config/routes.rb
Rails.application.routes.draw do
  resources :dvds
  resources :cart_items
  resources :baskets
  resources :films
  resources :people
  resources :countries
  resources :genres
  resources :users

  root 'films#index'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_current_user

  private

  def set_current_user
    @current_user = User.where(id: session[:user_id]).first
  end

  def check_authentication
    unless @current_user
      render_error "Доступ без авторизации запрещен", url: login_path
    end
  end

  def render_error(message = 'Доступ запрещен', options = {})
    flash[:danger] = message
    url = options[:url] || root_path
    redirect_to url
  end

  def authenticate_user(user)
    session[:user_id] = user.id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render 'error_messages_for', object: object
  end

  def copyright_years
    start = 2016
    finish = Date.today.year
    "© #{start == finish ? start : "#{start} — #{finish}"}"
  end

end

app/views/application/_error_messages_for.html.haml
-if object.errors.present?
  .panel.panel-danger
    .panel-heading При сохранении произошли ошибки
    .panel-body
      %ul.text-danger
        -object.errors.full_messages.each do |msg|
          %li=msg

app/views/application/_flash_messages.html.haml
-flash.each do |key,msg|
  .alert{class: "alert-#{key}"}=msg

app/views/application/_footer.html.haml
.row
  .col-md-9
    %br
    =copyright_years

app/views/application/_topbar.html.haml
%nav.navbar.navbar-default.navbar-static-top.navbar-inverse
  .container
    .navbar-header
      =button_tag type: 'button', class: 'navbar-toggle collapsed', data: {toggle: 'collapse', target: '#navbar-collapse'} do
        %span.sr-only Показать/скрыть меню
        =fa_icon 'bars'
      =link_to t('app.name'), root_path, class: 'navbar-brand'
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li=link_to 'Фильмы', films_path
        %li=link_to 'Диски', dvds_path
        %li=link_to 'Персоны', people_path
        %li=link_to 'Жанры', genres_path
        %li=link_to 'Страны', countries_path
        -if User.edit_by?(@current_user)
          %li=link_to 'Пользователи', users_path
        -if User.edit_by?(@current_user)
          %li=link_to 'Заказы', baskets_path
        -else
          -if @current_user!=nil
            %li=link_to 'Корзина', baskets_path

      %ul.nav.navbar-nav.navbar-right
        -if @current_user
          %li.dropdown
            =link_to ?#, class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
              =@current_user.email
              =fa_icon 'angle-down'
            %ul.dropdown-menu
              %li=link_to 'Выход', logout_path
        -else
          %li=link_to 'Регистрация', new_user_path
          %li=link_to 'Вход', login_path